export {default as SolPage} from './SolPage'
export {default as Home } from './Home'
export {default as HTMLPage} from './HTMLPage'
export {default as AiPage} from './AiPage'
export {default as JavascriptPage} from './JavascriptPage'
export {default as PythonPage} from './PythonPage'
export {default as Projects} from './Projects'